//
// Generated file, do not edit! Created by nedtool 5.6 from PseudonymMessage.msg.
//

#ifndef __PSEUDONYMMESSAGE_M_H
#define __PSEUDONYMMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include <vanetza/security/basic_elements.hpp>
#include <vanetza/security/certificate.hpp>
#include <vanetza/security/signature.hpp>
#include <vector>
// }}

/**
 * Class generated from <tt>PseudonymMessage.msg:32</tt> by nedtool.
 * <pre>
 * packet PseudonymMessage
 * {
 *     simtime_t timestamp;                      // Timestamp of the message
 *     vanetza::security::Certificate certificate;  // Certificate of the sender
 *     vanetza::security::Certificate pseudonym;  // Generated pseudonym
 *     vanetza::security::ecdsa256::PublicKey public_key; // Public Key to be used in the pseudonym
 *     vanetza::security::EcdsaSignature signature; // Signature of the message
 *     string payload;                            // Payload of the message
 * }
 * </pre>
 */
class PseudonymMessage : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::simtime_t timestamp;
    vanetza::security::Certificate certificate;
    vanetza::security::Certificate pseudonym;
    vanetza::security::ecdsa256::PublicKey public_key;
    vanetza::security::EcdsaSignature signature;
    ::omnetpp::opp_string payload;

  private:
    void copy(const PseudonymMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PseudonymMessage&);

  public:
    PseudonymMessage(const char *name=nullptr, short kind=0);
    PseudonymMessage(const PseudonymMessage& other);
    virtual ~PseudonymMessage();
    PseudonymMessage& operator=(const PseudonymMessage& other);
    virtual PseudonymMessage *dup() const override {return new PseudonymMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual ::omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(::omnetpp::simtime_t timestamp);
    virtual vanetza::security::Certificate& getCertificate();
    virtual const vanetza::security::Certificate& getCertificate() const {return const_cast<PseudonymMessage*>(this)->getCertificate();}
    virtual void setCertificate(const vanetza::security::Certificate& certificate);
    virtual vanetza::security::Certificate& getPseudonym();
    virtual const vanetza::security::Certificate& getPseudonym() const {return const_cast<PseudonymMessage*>(this)->getPseudonym();}
    virtual void setPseudonym(const vanetza::security::Certificate& pseudonym);
    virtual vanetza::security::ecdsa256::PublicKey& getPublic_key();
    virtual const vanetza::security::ecdsa256::PublicKey& getPublic_key() const {return const_cast<PseudonymMessage*>(this)->getPublic_key();}
    virtual void setPublic_key(const vanetza::security::ecdsa256::PublicKey& public_key);
    virtual vanetza::security::EcdsaSignature& getSignature();
    virtual const vanetza::security::EcdsaSignature& getSignature() const {return const_cast<PseudonymMessage*>(this)->getSignature();}
    virtual void setSignature(const vanetza::security::EcdsaSignature& signature);
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PseudonymMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PseudonymMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PSEUDONYMMESSAGE_M_H

